apiVersion: batch/v1
kind: Job
metadata:
  name: utcTimeDate
spec:
  template:
    spec:
      containers:
      - name: utcTimeDate
        image: us-west1-docker.pkg.dev/juta-0816/go-code/utctimedate:11082025
        command: ["go", "run", "utc-time-date.go"]
        args: ["sleep 900"]
      restartPolicy: Never
  backoffLimit: 5

